Upgrade to sbt 1.11.7
Can't cross build sbt 2

```
java.lang.RuntimeException: unknown sbt version 2
	at scala.sys.package$.error(package.scala:30)
	at sbt.Defaults$.sbtPluginExtra(Defaults.scala:2664)
	at sbt.Classpaths$.$anonfun$pluginProjectID$1(Defaults.scala:3624)
	at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:229)
	at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:171)
	at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:88)
	at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:100)
	at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:95)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[error] unknown sbt version 2
[error] Use 'last' for the full log.
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```


- https://github.com/sbt/sbt/releases/tag/v1.11.4
- https://github.com/sbt/librarymanagement/commit/607ae8b9c75912c4c8bcad1ff5b741d4dee8fa8c
- https://github.com/sbt/sbt/commit/3e21938c207510d62062757fb1a29a9d7c5b7db4